"""Module with constants affecting the game."""

TIC_TIMEOUT = 0.1
BORDER_THICKNESS = 1

STAR_QUANTITY = 250
STAR_SYMBOLS = ('+', '*', '.', ':')
STAR_APPEARANCE_TIMEOUT = 100
DIM_LIFETIME = 20
BRIGHT_LIFETIME = 5
COMMON_LIFETIME = 3


SPACE_KEY_CODE = 32
LEFT_KEY_CODE = 260
RIGHT_KEY_CODE = 261
UP_KEY_CODE = 259
DOWN_KEY_CODE = 258
